name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cx_Freeze PyQt5 requests

    - name: Build EXE
      run: python setup.py build

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-sdk-installer
        path: build/exe.win32-3.13/  # Adjust path based on your Python version and build output

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: android-sdk-installer

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          This release includes the latest build of the Android SDK Platform Tools Installer.
        draft: false
        prerelease: false

    - name: Upload EXE to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/exe.win32-3.9/AndroidSDKInstaller.exe
        asset_name: AndroidSDKInstaller.exe
        asset_content_type: application/octet-stream